---
output: 
  pdf_document:
    latex_engine: pdflatex
    keep_tex: false
    dev: cairo_pdf
    template: svm-latex-resume.tex

title: "Résumé"
author: "Annelise Koster"
date: "8/31/2020 -- Update before applying"

fontawesome: TRUE
# geometry: margin=1in
geometry: "top=.5in, left =.5in, right=.5in, bottom=.75in"

# How can we get a hold of you?
email: annelisekoster1@gmail.com
phone: 817-437-5834
location: "Fayetteville, AR"
github: ak031
web: 
twitter: 
linkedin: "annelise-koster"
mainfont: cochineal
sansfont: Fira Sans
# monofont: Fira Code # I want to use this, but seems to choke on @
urlcolor: blue
fontsize: 11pt

includephoto: TRUE
myphoto: Annelise-Koster.jpg
# shift: "7in,-.25in" # this is default
photobigness: 1.75cm
# photozoom: ".2\textwidth" # this is default
---


<!-- Read more about Pandoc's [fenced_divs](https://pandoc.org/MANUAL.html#extension-fenced_divs) syntax -->

:::::: {.columns}
::: {.column width="60%" data-latex="{0.60\textwidth}"}

# Professional Experience

## University of Arkansas - Resident Assistant
- Assist with the planning, implementation and evaluation of residence hall events
- Attend, participate and contribute to weekly staff meetings
- Perform several administrative duties, including room inspections, writing incident reports and submitting maintenance requests
- Enforce and implement university and campus policies
- Advise residents on academic and personal concerns

## Kanakuk - Dining Hall Staff
- Prepped and cleaned the dining hall and kitchen as well as served meals to 400+ people each day
- Coordinated the salad bar - organizing with the cooks to ensure we had enough produce, stocking and cleaning the salad station and training new staff on how to run the salad bar

## ARK Trading - Procurement Coordinator
- Grew electrical department sales by over 200% by expanding and optimizing the product range
- Purchased and managed $100,000 USD in inventory, while negotiating deals, promotions and discounts with suppliers
- Maintained the department's pricing and mark-ups

## Crete Gymnastics Club - Coach
- Coached gymnasts aged 8-17
- Developed daily, weekly and monthly training programs for girls in the national team development squad

# Organizations

## Honors Student Executive Board
- Analyze, critique and offer suggestions for changes and improvements that could be made to the Walton Honors Program
- Responsible for helping to plan virtual interactive events

:::
::: {.column width="2%" data-latex="{0.02\textwidth}"}
\ 
<!-- an empty div with an empty character to serve as a column sep -->
:::
:::::: {.column width="38%" data-latex="{0.38\textwidth}"}

# Education

 
## Undergraduate Program
Bachelor of Science in Data Science with a Business Data Analytics Concentration
- expected May 2023
- GPA 4.0

# Projects

## NSF EPSCoR Track 1 Undergraduate Research Assistantship Fellow
- Help increase the extent of data science education in Arkansas

## ARK Trading - Customer Service Intern
- Researched, configured and customized a system to measure key performance metrics such as number of customers helped, wait times and service times to allow ARK Trading to gather data to increase the efficiency of their order fulfillment as well as their deliveries

## Doug McMillion Innovation Studio
- Used rapid prototyping, lean canvas methodology, and design thinking to develop an idea that would decrease reverse logistics for clothing retailers
- Created a prototype of an app - Perfit

# Languages and Awards

## Chancellor's List (2018-2020)
## Sportswoman of the Year - Namibian Gymnastics Federation
## English - fluent
## Afrikaans - conversational
## German - passable


:::
::::::

<!-- If you want another page, this is how you can do it... -->

<!-- \newpage

:::::: {.columns}
::: {.column width="60%" data-latex="{0.60\textwidth}"}




:::
::: {.column width="2%" data-latex="{0.02\textwidth}"}
\


:::
:::::: {.column width="38%" data-latex="{0.38\textwidth}"}


:::
::::::

-->